class GreetingsController < ApplicationController
  def hello
  @words = ['swum',
	'nonseraphic',
	'triaxiality',
	'unsawn',
	'unfacaded',
	'semiprotective',
	'presubstitute',
	'humoristic',
	'parolable',
	'kioto',
	'enlightenment',
	'coordinately',
	'especial',
	'undetachable',
	'seriplane',
	'hale',
	'eolic',
	'allay',
	'exosporal',
	'shawm',
	'discount',
	'superuniversal',
	'unlaunched',
	'corfam',
	'divaricated',
	'gradation',
	'khafajeh',
	'ridiculosity',
	'pseudogenerical',
	'uncritically',
	'interjaculating',
	'predonate',
	'aliza',
	'lohrmann',
	'diphthongia',
	'intercharging',
	'excepable',
	'honeyedness',
	'brunet',
	'campion',
	'ungovernably',
	'undergoverness',
	'phebe',
	'd''inzeo',
	'petrolina',
	'invading',
	'formularization',
	'radiothorium',
	'sejant',
	'modifiableness',
	'neumster',
	'altaic',
	'epidermic',
	'antireducer',
	'abuttal',
	'somebodies',
	'dyspnoeic',
	'amethystine',
	'unextolled',
	'anglicism',
	'osmous',
	'rolland',
	'cumberless',
	'hypertragic',
	'debutant',
	'indocility',
	'srinivasa',
	'esthesis',
	'reluctant',
	'episkotister',
	'immunologic',
	'nummular',
	'arabesquely',
	'shivery',
	'cephalalgia',
	'orts',
	'georgene',
	'tetracid',
	'repaneling',
	'unchewable',
	'nonephemeral',
	'phosphorating',
	'federalism',
	'dubitatively',
	'senhorita',
	'imposing',
	'underclerk',
	'spectral',
	'lethargize',
	'troland',
	'algesic',
	'toughness',
	'unincluded',
	'multitoned',
	'protophloem',
	'galop',
	'semiporcelain',
	'phidias',
	'rarity',
	'adjacently']
    render('hello.html.erb')
  end

  def goodbye
    @af = [
  'Laren Trentelman',
  'Bhaidas Drinkall',
  'Pilvikki Bhuwad',
  'Danille Tveekrem',
  'Soumeya Dodus',
  'Du Kerrane',
  'Luois Stavenuiter',
  'Takura Ferencz',
  'Bakhaw Kalkavan',
  'Zatella Wasem',
  'Sirpa Hethanandani',
  'Atsuhiko Kagua',
  'Bamba Armenise',
  'Ojegba Decarlo',
  'Simmie Kijzer',
  'Emily Hotchin',
  'Nazneen Corado',
  'Agatino Lugovstov',
  'Kiyomichi Marsol',
  'Milita Jory',
  'Novin Trovin',
  'Behadin Dulac',
  'Sanbao Tachon',
  'Cambri Hollet',
  'Birutta Drance',
  'Shruthi Briley',
  'Moani Namour',
  'Xandra Eremia',
  'Valney Denisiuk',
  'Shabeer Behrenberg',
  'Baird Bresolin',
  'Morina Molena',
  'Gaurab Linow',
  'Shreela Makhkamov',
  'Shambo Farabaugh',
  'Ichrak Fischnaller',
  'Townes Vajda',
  'Davester Salz',
  'Beaumont Adeleke',
  'Tamires Manding',
  'Kadeem Horace',
  'Phoe Kafarakis',
  'Asofa Buffery',
  'Aret Mcfadin',
  'Welli Mule',
  'Xiuqiong Miera',
  'Tubardh Kobuck',
  'Yucel Mykael',
  'Laynce Huckabay',
  'Ambition Bolanger',
  'Abdullaziz Bewick',
  'Yo Aubry',
  'Gencer Glascock',
  'Haji Valsassina',
  'Bellini Spires',
  'Soochung Louzoum',
  'Silvinija Palay',
  'Vasti Haagensen',
  'Yumeiji Baligian',
  'Socrate Auzias',
  'Turuica Capitanescu',
  'Desire Heltimoinen',
  'Shawnique Dicello',
  'Jama Plana',
  'Takuya Millington',
  'Shadard Herner',
  'Odjel Honer',
  'Denicio Manoun',
  'Csherian Platisa',
  'Dicu Gaál',
  'Barlow Keigher',
  'Sammantha Lugar',
  'Bobi Vallez',
  'Teshima Tiokner',
  'Garen Hooymaayer',
  'Natalie Faiziev',
  'Justiin Arnautovic',
  'Benji Tol',
  'Nicco Herzet',
  'Kishor Shivaskar',
  'Charmel Markee',
  'Dincer Piekutowski',
  'Bernadete Silvertand',
  'Kelci Tsvetov',
  'Arijan Barsumian',
  'Uygur Umeya',
  'Bartholome Fujinuma',
  'Sanrak Hickel',
  'Erzsi Condellone',
  'Gresham Gnevanov',
  'Shamsher Otaola',
  'Gillian Rintoul',
  'Zengtian Skoryakin',
  'Azalia Aarsland',
  'Tiansheng Artiles',
  'Lebrak Budziak',
  'Jagriti Raitolehto',
  'Akushla Randl',
  'Rengga Huntingdale',
  'Peggie Nikonenko'
 ]
    render('goodbye.html.erb')
  end
end
